pipeline {
    agent {
        docker {
            image 'python'
            args '-u root' // Chạy với quyền root
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'pip3 install -r s05/python-simple-app/requirements.txt'
            }
        }

        stage('run') {
            steps {
                sh 'echo "Start"'
                sh 'python3 s05/python-simple-app/app.py &'
                sh 'echo "End"'
            }
        }

        stage('test') {
            steps {
                sh 'sleep 10 && curl -s localhost:8000'
               
            }
        }

        stage('cleanup') {
            steps {
                sh 'netstat -tuln | awk '$4 ~ /:8000$/ {split($NF,a,"/"); print a[1]}' | xargs kill -9'
            }
        }

    }
}
