pipeline {
    agent {
        docker {
            image 'python'
            args '-u root --name python-app-without-dockerfile' // Chạy với quyền root
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'pip3 install -r s05/python-simple-app/requirements.txt'
            }
        }

        stage('run') {
            steps {
                sh 'echo "Start"'
                sh 'python3 s05/python-simple-app/app.py &'
                sh 'echo "End"'
            }
        }

        stage('test') {
            steps {
                sh 'sleep 10 && curl -s localhost:8001'
               
            }
        }

        stage('cleanup') {
            steps {
                sh 'apt-get update && apt-get install psmisc'
                sh 'which fuser'
                sh 'fuser -k 8001/tcp'
            }
        }

    }
}
